GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "notes": [],
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "notes": [],
    "username": "mluukkai",
    "name": "Matti Luukkainen",
    "password": "sekret"
}